# -*- coding: utf-8 -*-
"""AlgBio_ATV5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KPGr3lqX3s-Uwy3t8fiY8S-7yEwHaj7A
"""

!pip install Biopython

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

# Caminho para o arquivo FASTA
fasta_file = "/content/drive/MyDrive/AlgBio/dengue_virus_completo.fasta"

# Lista para armazenar os registros SeqRecord
records = []

# Leitura do arquivo FASTA
for seq_record in SeqIO.parse(fasta_file, "fasta"):
    # Obtendo o identificador da sequência
    seq_id = seq_record.id
    # Obtendo a sequência
    sequence = str(seq_record.seq)

    # Traduzindo os três frames
    for frame in range(3):
        dna_seq = Seq(sequence[frame:])
        protein_seq = dna_seq.translate()

        # Letra inicial e final do trecho desejado
        letra_inicial = "M"  # Letra inicial do trecho
        letra_final = "*"    # Letra final do trecho

        # Procurando os trechos
        pos_inicial = None
        protein_num = 1
        i = 0
        while i < len(protein_seq):
            if protein_seq[i] == letra_inicial:
                # Apenas fixa a posição inicial uma vez
                if pos_inicial is None:
                    pos_inicial = i
            elif protein_seq[i] == letra_final:
                # Encontrou a posição final
                if pos_inicial is not None:
                    # Criando um novo SeqRecord para o trecho encontrado
                    trecho_encontrado = protein_seq[pos_inicial:i + 1]
                    record = SeqRecord(trecho_encontrado, id=f"{seq_id}, Frame {frame + 1}, proteína {protein_num}", description="")
                    # Adicionando o SeqRecord à lista
                    records.append(record)
                    protein_num += 1
                    # Resetar posição inicial para continuar a busca
                    pos_inicial = None
            i += 1

# Escrevendo os registros SeqRecord em um novo arquivo FASTA
SeqIO.write(records, "/content/drive/MyDrive/AlgBio/saida_possiveis_trechos.fasta", "fasta")